name: Infracost Scan

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  infracost-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Infracost Scan
        uses: infracost/actions/scan@a1f1aab438c2d0e642e7cd596a1c8750c7c75a5e
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          path: .
